### ISSUE TITLE
Not fixing FLS issue

### ISSUE THREAD

**Issue by vsmarimuthu** [patronmanager/apex-dml-manager#10]
My Code is like this
 ` 
ProviderRecordQuestion__c questionObj = new ProviderRecordQuestion__c(); 
questionObj.CPAHomes__c = cpaHomeId;
 questionObj.Actor__c = stractorId;
DMLManager.upsertAsUser(questionObj);
`

but always i am getting error from checkmarx scanner

![Untitled](https://user-images.githubusercontent.com/22540745/119930899-fc623f80-bf9d-11eb-8301-630be1b7491f.png)

**Comment by daveespo** [comment]
When did you run your scan? The Checkmarx scanner is colossally broken as of about 2 weeks ago:

https://partners.salesforce.com/0D54V00005PEQbf

**Comment by vsmarimuthu** [comment]
![image](https://user-images.githubusercontent.com/22540745/119975032-03577500-bfd3-11eb-9c5e-a68ab42a752c.png)

Today only I ran the scan

**Comment by daveespo** [comment]
Yeah, this is a regression in the Checkmarx rules -- it has nothing to do with DMLManager

**Comment by vsmarimuthu** [comment]
@daveespo . Will wait for salesforce to fix it. Thanks a lot.
