### ISSUE TITLE
Security Scaner Issue: SOQL SOSL Injection

### ISSUE THREAD

**Issue by dlisovsky** [patronmanager/apex-dml-manager#16]
<img width="1419" alt="image" src="https://github.com/patronmanager/apex-dml-manager/assets/4610433/fbbf6fc7-3858-4f23-bd88-2c05a296f558">

`L 213: result.putAll((Database.query('SELECT ' + fieldList + ' FROM ' + objType.getDescribe().getName() + ' WHERE Id IN :seenIds')));
`

Any idea how to fix that?

**Comment by daveespo** [comment]
That's a false positive. Include something like this in your false positives doc and it will be accepted:

DMLManager
The DMLManager class (specifically the getExistingRecords method) constructs a dynamic query to execute its operations. The code that builds and executes this dynamic query is being called out as a SOQL SOSL Injection vulnerability. However, the input to the dynamic component of the query comes only from DescribeFieldResult and/or collections of typed objects (specifically, their Ids). No user input is used to construct this query.
